source 'http://rubygems.org'

gem 'pg'

gem 'grape', '~> 0.13.0'

gem 'activerecord',  '~> 4.2.1', require: 'active_record'
gem 'otr-activerecord'
gem 'grape-swagger', '~> 0.10.2'
gem 'rack',          '~> 2.0.3'


group :test do
  gem 'rspec',     '~> 3.3'
  gem 'rack-test', '~> 0.8.2'
end


group :development, :test do
  gem 'rake', '~> 10.4.2'
  gem 'pry'
end
